FROM nginx:1.21.3-alpine

COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./conf.d/bmf-tech-client.conf /etc/nginx/conf.d/bmf-tech-client.conf

RUN ln -sf /dev/stdout /var/log/nginx/access_bmf_tech_client.log \
    && ln -sf /dev/stderr /var/log/nginx/error_bmf_tech_client.log \